---
apiVersion: v1
kind: Namespace
metadata:
  name: ghost

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:alpine
          env:
            - name: url
              value: http://yourdomain.com
            - name: NODE_ENV
              value: production
            - name: database__client
              value: sqlite3
            - name: database__connection__filename
              value: /var/lib/ghost/content/data/ghost.db
            - name: database__useNullAsDefault
              value: "true"
            - name: database__debug
              value: "false"
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-volume
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-volume
          hostPath:
            path: /opt/volumes/ghost/blog

---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost
spec:
  selector:
    app: ghost
  ports:
    - name: http
      port: 80
      targetPort: 2368

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost
  namespace: ghost
spec:
  rules:
    - host: yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ghost
                port:
                  name: http
